//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTPHIEUNHAP
    {
        public int MaPN { get; set; }
        public Nullable<int> MaNL { get; set; }
        public Nullable<int> MaDon { get; set; }
        public int SL { get; set; }
        public string DVT { get; set; }
        public Nullable<double> GiaNhap { get; set; }
        public Nullable<double> GiamGia { get; set; }
    
        public virtual DONNHAPHANG DONNHAPHANG { get; set; }
        public virtual NGUYENLIEU NGUYENLIEU { get; set; }
    }
}
