//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class COFFEE_HOUSEEntities : DbContext
    {
        public COFFEE_HOUSEEntities()
            : base("name=COFFEE_HOUSEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BAN> BAN { get; set; }
        public virtual DbSet<CTPHIEUNHAP> CTPHIEUNHAP { get; set; }
        public virtual DbSet<CTHD> CTHD { get; set; }
        public virtual DbSet<DONNHAPHANG> DONNHAPHANG { get; set; }
        public virtual DbSet<HOADON> HOADON { get; set; }
        public virtual DbSet<KHUYENMAI> KHUYENMAI { get; set; }
        public virtual DbSet<LOAI_BAN> LOAI_BAN { get; set; }
        public virtual DbSet<LOAI_NGUYENLIEU> LOAI_NGUYENLIEU { get; set; }
        public virtual DbSet<LOAI_SANPHAM> LOAI_SANPHAM { get; set; }
        public virtual DbSet<LOAI_TAIKHOAN> LOAI_TAIKHOAN { get; set; }
        public virtual DbSet<NCC> NCC { get; set; }
        public virtual DbSet<NGUYENLIEU> NGUYENLIEU { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIEN { get; set; }
        public virtual DbSet<SANPHAM> SANPHAM { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TAIKHOAN> TAIKHOAN { get; set; }
        public virtual DbSet<TK_QUYEN> TK_QUYEN { get; set; }
    }
}
