//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class NGUYENLIEU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NGUYENLIEU()
        {
            this.CTPHIEUNHAP = new HashSet<CTPHIEUNHAP>();
        }
    
        public int MaNL { get; set; }
        public Nullable<int> MaNCC { get; set; }
        public string TenNL { get; set; }
        public Nullable<int> LoaiNL { get; set; }
        public int SLTon { get; set; }
        public string DVT { get; set; }
        public int TrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTPHIEUNHAP> CTPHIEUNHAP { get; set; }
        public virtual LOAI_NGUYENLIEU LOAI_NGUYENLIEU { get; set; }
        public virtual NCC NCC { get; set; }
    }
}
