//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAIKHOAN
    {
        public int MaTK { get; set; }
        public Nullable<int> MaNV { get; set; }
        public string Username { get; set; }
        public string MatKhau { get; set; }
        public Nullable<int> LoaiTK { get; set; }
        public Nullable<int> Quyen { get; set; }
        public int TrangThai { get; set; }
    
        public virtual LOAI_TAIKHOAN LOAI_TAIKHOAN { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual TK_QUYEN TK_QUYEN { get; set; }
    }
}
